### PR TITLE
Add resource section

### PR DESCRIPTION
**Pull request by ctmbl**
Heavily draft for now

Non exhaustive TODO:
- [x] create /resources
- [x] create drop down for various resources types
- [x] use shortcodes instead of unsafe render goldmark parameter
- [x] add /resources to menu
- [x] explore better options for resources listing
  - [x] update `/layouts/resources/resources.html` to recursively display `/resources` sections and pages
    https://gohugo.io/content-management/sections/
    https://gohugo.io/methods/page/issection/
  - [x] recursively list sections in details/summary block
  - [x] use nested sections and hierarchic pages
- [x] add a taxonomy to resources: 
  - [x] either: `tags` and update the `tags` taxonomy list to separate posts and resources
- [x] disable reading time for this page
- [x] ~~add hierarchic history at the top page like (but not exactly like):~~
image
**reported to #72**
- [x] sort `/tags` by alphabetical order instead of grouping by date (tags assoicated with resoyrces only don't have date)
- [x] create a very basic resource page see #72 for future ideas about it

## References

Non exhaustive list of resources I used:  

about target and `_blank` vuln:
- https://stackoverflow.com/a/17711167
- https://dev.to/ben/the-targetblank-vulnerability-by-example
- https://mathiasbynens.github.io/rel-noopener/

dropdowns:
- https://dev.to/asyraf/how-to-add-dropdown-in-markdown-o78

GMF:
- https://github.github.com/gfm

about unsafe:
- https://discourse.gohugo.io/t/raw-html-omitted-in-templates/43375/9
- https://gohugo.io/getting-started/configuration-markup/#rendererunsafe
- https://github.com/yuin/goldmark?tab=readme-ov-file#built-in-extensions :
  > This extension does not filter tags defined in 6.11: Disallowed Raw HTML (extension). If you need to filter HTML tags, see Security.
- https://github.com/yuin/goldmark?tab=readme-ov-file#security

CSS and hugo layout:
- https://iscsc.fr/posts/introducing-poison/#custom-css
- https://iscsc.fr/posts/introducing-poison/#the-sidebar-menu
- https://gohugobrasil.netlify.app/themes/customizing/
- https://gohugo.io/templates/types/#structure layout folder structure
- https://gohugo.io/templates/content-view/#which-template-will-be-rendered template look order priority
- https://gohugo.io/templates/lookup-order/ template look order priority (also)

### CODE REVIEW

**Comment by ctmbl** [comment]
Screenshot_20240422_141716
Screenshot_20240422_141639

WIP visual rendering

**Comment by ctmbl** [comment]
@ZynoXelek @atxr @Turtyo 
you can check out the first iteration of the resources here: https://dev.iscsc.fr/

**Comment by ctmbl** [comment]
the hierarchy history, sort of path in the resources, is called a breadcrumnb in english:
- https://gohugo.io/methods/page/ancestors/ an example of such a breadcrumb in HUGO
- https://www.frontendplanet.com/css-breadcrumb-examples/ examples of breadcrumb CSS

**Review by ZynoXelek — APPROVED** [review]
Nice-looking and functionnal implementation!

**Pull request merged**
